apiVersion: v1
kind: Service
metadata:
  name: relationship-engine-api
  namespace: relationship-engine
  labels:
    app.kubernetes.io/name: relationship-engine-api
    app.kubernetes.io/part-of: pao-platform
    app.kubernetes.io/component: api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8001
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: relationship-engine-api
---
apiVersion: v1
kind: Service
metadata:
  name: relationship-engine-postgres
  namespace: relationship-engine
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: pao-platform
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: relationship-engine-redis
  namespace: relationship-engine
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: pao-platform
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: relationship-engine-kuzu
  namespace: relationship-engine
  labels:
    app.kubernetes.io/name: kuzu
    app.kubernetes.io/part-of: pao-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: bolt
      port: 7687
      targetPort: 7687
      protocol: TCP
  selector:
    app.kubernetes.io/name: kuzu