"""Memory Engine - Hybrid memory system for AI companions."""

from .models import (
    MemoryType,
    EpisodicMemory,
    SemanticMemory,
    EmotionalMemory,
    RelationshipMemory,
    TimelineMemory,
    PreferenceMemory,
    MemoryFilter,
    RecallQuery,
    RecallResponse,
    RecallContext,
    RecalledMemory,
    MemoryWrite,
    MemoryRead,
    MemoryUpdate,
    MemoryDelete,
    MemoryResponse,
    ConsolidationJob,
    ConsolidationStatus,
    ClusterResult,
    FactExtraction,
    ConsolidationReport,
    ConsolidationCandidate,
    ConsistencyIssue,
    ConsistencyCheck,
    ConsistencyReport,
    ContradictionType,
)
from .repositories import (
    MemoryRepository,
    PostgresRepository,
    QdrantRepository,
    KuzuRepository,
    RedisRepository,
)
from .services import (
    MemoryService,
    ConsolidationService,
    RecallService,
    ConsistencyService,
    ExportService,
)
from .api import (
    memory_router,
    initialize_repositories,
    close_repositories,
    get_memory_service,
    get_consolidation_service,
    get_recall_service,
    get_consistency_service,
    get_export_service,
)

__version__ = "0.1.0"

__all__ = [
    # Models
    "MemoryType",
    "EpisodicMemory",
    "SemanticMemory",
    "EmotionalMemory",
    "RelationshipMemory",
    "TimelineMemory",
    "PreferenceMemory",
    "MemoryFilter",
    "RecallQuery",
    "RecallResponse",
    "RecallContext",
    "RecalledMemory",
    "MemoryWrite",
    "MemoryRead",
    "MemoryUpdate",
    "MemoryDelete",
    "MemoryResponse",
    "ConsolidationJob",
    "ConsolidationStatus",
    "ClusterResult",
    "FactExtraction",
    "ConsolidationReport",
    "ConsolidationCandidate",
    "ConsistencyIssue",
    "ConsistencyCheck",
    "ConsistencyReport",
    "ContradictionType",
    # Repositories
    "MemoryRepository",
    "PostgresRepository",
    "QdrantRepository",
    "KuzuRepository",
    "RedisRepository",
    # Services
    "MemoryService",
    "ConsolidationService",
    "RecallService",
    "ConsistencyService",
    "ExportService",
    # API
    "memory_router",
    "initialize_repositories",
    "close_repositories",
    "get_memory_service",
    "get_consolidation_service",
    "get_recall_service",
    "get_consistency_service",
    "get_export_service",
]